[package]
name = "libaris-rs"
version = "0.1.0"
authors = ["Avi Weinstock <aweinstock314@gmail.com>"]

[dependencies]
#either = "1.5.0"
frunk = "0.2.2"
jni = "0.10.2"
nom = "4.1.1"
petgraph = "0.4.13"
xml-rs = "0.8.0"

[build-dependencies]
cbindgen = "*"

[lib]
crate_type = ["cdylib"]
